version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
      - "./log:/verdaccio/log"  
networks:
  node-network:
    driver: bridge
